# Generated by Django 5.1 on 2024-09-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scans", "0013_session_seca_measurement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the procedure", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="The description of the procedure"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("not_started", "Not Started"),
                        ],
                        help_text="The status of the procedure",
                        max_length=255,
                    ),
                ),
                (
                    "outputs",
                    models.JSONField(
                        blank=True, help_text="The outputs of the procedure", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the procedure was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the procedure was last updated",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The session associated with this procedure",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="scans.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedure",
                "verbose_name_plural": "Procedures",
            },
        ),
    ]
