# Generated by Django 5.1 on 2024-08-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["session_id"],
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
            },
        ),
        migrations.RemoveField(
            model_name="session",
            name="session_date",
        ),
    ]
