# Generated by Django 5.1 on 2024-08-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavioral", "0001_initial"),
        ("scans", "0007_alter_session_scan_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="questionnaire_response",
            field=models.ForeignKey(
                help_text="The questionnaire response associated with this session",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="behavioral.questionnaireresponse",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="time_between_scan_and_questionnaire",
            field=models.DurationField(
                blank=True,
                help_text="The time between the scan and the questionnaire",
                null=True,
            ),
        ),
    ]
