# Generated by Django 5.1 on 2024-08-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0008_session_questionnaire_response_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
            },
        ),
        migrations.RenameField(
            model_name="session",
            old_name="datetime",
            new_name="timestamp",
        ),
    ]
