# Generated by Django 5.1 on 2024-08-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0010_session_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="session_id",
            new_name="origin_session_id",
        ),
    ]
