# Generated by Django 5.1 on 2024-09-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0011_rename_session_id_session_origin_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="date",
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Unique identifier for the session", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="time",
            field=models.TimeField(editable=False, null=True),
        ),
    ]
