# Generated by Django 5.1.1 on 2024-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0013_session_seca_measurement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="age_at_scan",
            field=models.FloatField(
                blank=True,
                help_text="Age of the subject at the time of the scan",
                null=True,
            ),
        ),
    ]
