# Generated by Django 5.1.1 on 2024-10-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0014_session_age_at_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="rawdata_path",
            field=models.FilePathField(
                blank=True,
                help_text="Path to the raw data associated with this session",
            ),
        ),
    ]
