# Generated by Django 5.1.1 on 2024-10-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0015_session_rawdata_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="rawdata_path",
            field=models.FilePathField(
                blank=True,
                help_text="Path to the raw data associated with this session",
                max_length=300,
            ),
        ),
    ]
