# Generated by Django 5.1 on 2024-08-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='studies',
        ),
    ]
