# Generated by Django 5.1 on 2024-08-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0005_alter_subject_subject_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="last_name",
        ),
        migrations.AddField(
            model_name="subject",
            name="name",
            field=models.CharField(
                blank=True, help_text="Name of the subject", max_length=100
            ),
        ),
    ]
