# Generated by Django 5.1 on 2024-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subjects",
            "0006_remove_subject_first_name_remove_subject_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_id",
            field=models.CharField(
                help_text="Unique identifier for the subject",
                max_length=50,
                unique=True,
            ),
        ),
    ]
