# Generated by Django 5.1 on 2024-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0007_alter_subject_subject_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="questionnaire_id",
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_code",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for questionnaires",
                max_length=50,
            ),
        ),
    ]
