# Generated by Django 5.1 on 2024-09-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_study_lab"),
        ("subjects", "0008_remove_subject_questionnaire_id_subject_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="conditions",
            field=models.ManyToManyField(
                help_text="Conditions associated with this subject",
                related_name="subjects",
                to="studies.condition",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="groups",
            field=models.ManyToManyField(
                help_text="Groups associated with this subject",
                related_name="subjects",
                to="studies.group",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="studies",
            field=models.ManyToManyField(
                help_text="Studies associated with this subject",
                related_name="subjects",
                to="studies.study",
            ),
        ),
    ]
