# Generated by Django 5.1.1 on 2025-09-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0009_subject_conditions_subject_groups_subject_studies"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="uid",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the subject (UUID)",
                max_length=50,
            ),
        ),
    ]
