# Generated by Django 5.1.1 on 2025-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0009_subject_conditions_subject_groups_subject_studies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_id",
            field=models.CharField(
                help_text="Unique identifier for the subject", max_length=50
            ),
        ),
    ]
