# Generated by Django 5.1 on 2024-08-29 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0007_alter_subject_subject_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questionnaire",
                    models.CharField(
                        help_text="The name of the questionnaire", max_length=50
                    ),
                ),
                (
                    "full_response",
                    models.JSONField(help_text="The response to the questionnaire"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject associated with this questionnaire response",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_responses",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire Response",
                "verbose_name_plural": "Questionnaire Responses",
            },
        ),
    ]
