# Generated by Django 5.1 on 2024-08-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("behavioral", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaireresponse",
            name="questionnaire",
        ),
    ]
