# Generated by Django 5.1 on 2024-09-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavioral", "0002_remove_questionnaireresponse_questionnaire"),
        ("subjects", "0008_remove_subject_questionnaire_id_subject_subject_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="SECAMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_measurement",
                    models.JSONField(help_text="The measurement from the SECA scale"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        editable=False,
                        help_text="The timestamp of the measurement",
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        editable=False,
                        help_text="The date of the measurement",
                        null=True,
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        editable=False,
                        help_text="The time of the measurement",
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        editable=False,
                        help_text="The date of birth of the subject",
                        null=True,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Unknown"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "subject_code",
                    models.CharField(
                        blank=True,
                        help_text="The subject code associated with the measurement",
                        max_length=50,
                    ),
                ),
                (
                    "bmi",
                    models.FloatField(
                        editable=False, help_text="The BMI of the subject", null=True
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        editable=False, help_text="The weight of the subject", null=True
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        editable=False, help_text="The height of the subject", null=True
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject associated with this measurement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seca_measurements",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "SECA Measurement",
                "verbose_name_plural": "SECA Measurements",
            },
        ),
    ]
